### PR TITLE
feat(defaults): add scanner settings

### PR DESCRIPTION
**Pull request by RubenVinke**

### CODE REVIEW

**Comment by omeaart** [comment]
@RubenVinke why include "Pos" in the name of the setting? The whole app settings structure is set up to allow providing different values per app already based on the UserAgent.

**Comment by RubenVinke** [comment]
We've done that for years so using it here is a way to stay consistent.

**Comment by omeaart** [comment]
@RubenVinke but keeping adding new deprecated settings is not moving forward really 🤪 
How would you propose switching to the new way of handling this?

**Review by omeaart — APPROVED** [review]

**Comment by RubenVinke** [comment]
@omeaart Make a little project where we purge all the `App:Pos:` settings, this will probably lead to some friction because they'd need to add those new settings on prod.

**Pull request merged**
