### PR TITLE
feat: add app setting

### PR DESCRIPTION
**Pull request by jibbewillem**
https://n6k.atlassian.net/browse/OPTR-32674

### CODE REVIEW

**Comment by omeaart** [comment]
@jibbewillem you sure you want `int[]`? We are moving to the StringIDs fcourse.

**Comment by jibbewillem** [comment]
@omeaart I originally typed them as strings, but got back integers. Perhaps this service is not using string ID's yet? I can change it back to string, since it does not impact the side of POS, but perhaps better to check why they are integers in the first place?

**Comment by omeaart** [comment]
@jibbewillem the backend does nothing with appsetting values. Only when there is a record in this repo without Converted set to true AND the setting for fallback handling in EVA is set to true. So what you set in the setting is what you will get back.

**Comment by jibbewillem** [comment]
@omeaart You are correct. I made a mistake and converted the input to integers. Note: Values need to be entered as "1, 2, 3" in Eva Admin.

image


I'll chang the type for this PR and in POS.

**Review by omeaart — APPROVED** [review]

**Pull request merged**
